// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh6F9Rh31ItxNxCmGbZB8J8do20C8YQXc',
    appId: '1:459424282585:web:d59eba04c1eb8548b9cbc8',
    messagingSenderId: '459424282585',
    projectId: 'pl-f6ea7',
    authDomain: 'pl-f6ea7.firebaseapp.com',
    storageBucket: 'pl-f6ea7.firebasestorage.app',
    measurementId: 'G-KXWYKQ68CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0m7yDOu7GBqaZzSzCyQ11UVxQTxW2MbU',
    appId: '1:459424282585:android:67b70b146a209ad6b9cbc8',
    messagingSenderId: '459424282585',
    projectId: 'pl-f6ea7',
    storageBucket: 'pl-f6ea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd8n77Zvp7m12nHBTnkH-2t_0C_JLjB08',
    appId: '1:459424282585:ios:3ca611f540bcf8deb9cbc8',
    messagingSenderId: '459424282585',
    projectId: 'pl-f6ea7',
    storageBucket: 'pl-f6ea7.firebasestorage.app',
    iosBundleId: 'com.example.premierLeague',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd8n77Zvp7m12nHBTnkH-2t_0C_JLjB08',
    appId: '1:459424282585:ios:3ca611f540bcf8deb9cbc8',
    messagingSenderId: '459424282585',
    projectId: 'pl-f6ea7',
    storageBucket: 'pl-f6ea7.firebasestorage.app',
    iosBundleId: 'com.example.premierLeague',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh6F9Rh31ItxNxCmGbZB8J8do20C8YQXc',
    appId: '1:459424282585:web:6a7077003e64bc62b9cbc8',
    messagingSenderId: '459424282585',
    projectId: 'pl-f6ea7',
    authDomain: 'pl-f6ea7.firebaseapp.com',
    storageBucket: 'pl-f6ea7.firebasestorage.app',
    measurementId: 'G-SN6HJVDTLE',
  );
}
